name: reusable-workflow
on:
    workflow_call:
        inputs:
            artifact-name:
                description: 'Name of the artifact to deploy'
                required: false
                default: 'dist-files'
                type: string 
        secrets:
            mongo-secret-username:
                description: 'MongoDB Username'
                required: false
        outputs:
            result: 
                description: 'Outcome of the deployment'
                value: ${{ jobs.deploy.outputs.outcome}}
jobs:
    deploy:
        runs-on: ubuntu-latest
        outputs:
          outcome: ${{ steps.deploy-result.outputs.deployment-result }} 
        steps:
            - name: Deploy application
              run: echo "Deploying application..."
            - name: Get build artifacts
              uses: actions/download-artifact@v4
              with:
                name: ${{ inputs.artifact-name }}
            - name: Output contents
              run: ls
            - name: Use MongoDB Secret
              run: |
                echo "Using MongoDB username: ${{ inputs.mongo-secret-username }}"
            - name: Output deployment result
              id: deploy-result
              run : echo "deployment-result=success" >> $GITHUB_OUTPUT ";"
        